# File: environment.yml

name: streamlit-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - streamlit
  - pandas
  - plotly
  - google-cloud-bigquery
  - google-auth
  - google-auth-oauthlib
  - google-auth-httplib2
  - google-api-python-client
