name: app8.py
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit=1.22.0
  - pandas=1.3.0
  - plotly=5.2.1
  - google-cloud-bigquery=2.26.0
  - google-auth=2.6.0
  - python-dateutil=2.8.2
